package taskstore

const TaskQueueStatusCanceled = "canceled"
const TaskQueueStatusDeleted = "deleted"
const TaskQueueStatusFailed = "failed"
const TaskQueueStatusPaused = "paused"
const TaskQueueStatusQueued = "queued"
const TaskQueueStatusRunning = "running"
const TaskQueueStatusSuccess = "success"

const TaskDefinitionStatusActive = "active"
const TaskDefinitionStatusCanceled = "canceled"

const COLUMN_ALIAS = "alias"
const COLUMN_ATTEMPTS = "attempts"
const COLUMN_COMPLETED_AT = "completed_at"
const COLUMN_CREATED_AT = "created_at"
const COLUMN_DELETED_AT = "deleted_at"
const COLUMN_DETAILS = "details"
const COLUMN_ID = "id"
const COLUMN_DESCRIPTION = "description"
const COLUMN_IS_RECURRING = "is_recurring"
const COLUMN_METAS = "metas"
const COLUMN_MEMO = "memo"
const COLUMN_PARAMETERS = "parameters"
const COLUMN_OUTPUT = "output"
const COLUMN_RECURRENCE_RULE = "recurrence_rule"
const COLUMN_STARTED_AT = "started_at"
const COLUMN_STATUS = "status"
const COLUMN_TASK_ID = "task_id"
const COLUMN_TITLE = "title"
const COLUMN_UPDATED_AT = "updated_at"

const ASC = "asc"
const DESC = "desc"

const COLUMN_QUEUE_NAME = "queue_name"
const DefaultQueueName = "default"
